"""empty message

Revision ID: 1f0b35d73bd9
Revises: 9706b7f52ce7
Create Date: 2023-08-29 14:45:51.884809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f0b35d73bd9'
down_revision = '9706b7f52ce7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'explanation',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'explanation',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
