"""init table

Revision ID: 3df0d765ee4e
Revises: 
Create Date: 2023-12-06 12:42:36.889934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df0d765ee4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('meal_cost', sa.Integer(), nullable=False),
    sa.Column('ot_pay', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_id'), 'team', ['id'], unique=True)
    op.create_table('unit',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit_pay', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_id'), 'unit', ['id'], unique=True)
    op.create_table('position',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('salary_code', sa.Integer(), nullable=False),
    sa.Column('preset', sa.Integer(), nullable=False),
    sa.Column('standard_pay', sa.Integer(), nullable=False),
    sa.Column('sorting_index', sa.Integer(), nullable=False),
    sa.Column('is_leader', sa.Boolean(), nullable=False),
    sa.Column('is_child', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('unit_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_id'), 'position', ['id'], unique=True)
    op.create_table('draft',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('start_period', sa.Date(), nullable=False),
    sa.Column('end_period', sa.Date(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_id'), 'draft', ['id'], unique=True)
    op.create_table('employee',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('bank', sa.String(), nullable=False),
    sa.Column('bank_num_enc', sa.Text(), nullable=False),
    sa.Column('ssn_enc', sa.Text(), nullable=False),
    sa.Column('bank_book_file_nm', sa.String(), nullable=False),
    sa.Column('id_card_file_nm', sa.String(), nullable=False),
    sa.Column('sign_base64', sa.Text(), nullable=False),
    sa.Column('start_period', sa.Date(), nullable=False),
    sa.Column('end_period', sa.Date(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_id'), 'employee', ['id'], unique=True)
    op.create_table('attendance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('memo', sa.String(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('include_meal_cost', sa.Boolean(), nullable=False),
    sa.Column('ot_count', sa.Integer(), nullable=False),
    sa.Column('working_date', sa.String(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('incentive_pay', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('has_team', sa.Boolean(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    op.create_table('user_team',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_team')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_employee_id'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_draft_id'), table_name='draft')
    op.drop_table('draft')
    op.drop_index(op.f('ix_position_id'), table_name='position')
    op.drop_table('position')
    op.drop_index(op.f('ix_unit_id'), table_name='unit')
    op.drop_table('unit')
    op.drop_index(op.f('ix_team_id'), table_name='team')
    op.drop_table('team')
    # ### end Alembic commands ###
