"""empty message

Revision ID: 3fc73374f691
Revises: 
Create Date: 2023-08-04 18:03:03.433473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc73374f691'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('residence', sa.String(), nullable=False),
    sa.Column('gender_code', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('position_code', sa.Enum('STAFF', 'PART_TIME', 'ETC', name='position'), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_id'), 'worker', ['id'], unique=False)
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('daily_pay', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_id'), 'contract', ['id'], unique=False)
    op.create_table('personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank', sa.String(), nullable=False),
    sa.Column('bank_number_enc', sa.Text(), nullable=False),
    sa.Column('ssn_enc', sa.Text(), nullable=False),
    sa.Column('sign_enc', sa.Text(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_id'), 'personal', ['id'], unique=False)
    op.create_table('worklog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('working_date', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worklog_id'), 'worklog', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worklog_id'), table_name='worklog')
    op.drop_table('worklog')
    op.drop_index(op.f('ix_personal_id'), table_name='personal')
    op.drop_table('personal')
    op.drop_index(op.f('ix_contract_id'), table_name='contract')
    op.drop_table('contract')
    op.drop_index(op.f('ix_worker_id'), table_name='worker')
    op.drop_table('worker')
    # ### end Alembic commands ###
