"""init table

Revision ID: 4d301ab49cbc
Revises: 
Create Date: 2023-10-06 11:47:11.194960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d301ab49cbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('position_code', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('salary', sa.String(), nullable=False),
    sa.Column('default_wage', sa.Integer(), nullable=False),
    sa.Column('start_period', sa.Date(), nullable=False),
    sa.Column('end_period', sa.Date(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_id'), 'draft', ['id'], unique=True)
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('residence', sa.String(), nullable=False),
    sa.Column('gender_code', sa.Integer(), nullable=False),
    sa.Column('bank', sa.String(), nullable=False),
    sa.Column('bank_num_enc', sa.Text(), nullable=False),
    sa.Column('ssn_enc', sa.Text(), nullable=False),
    sa.Column('bank_book_file_nm', sa.String(), nullable=False),
    sa.Column('id_card_file_nm', sa.String(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_id'), 'employee', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_code', sa.Integer(), nullable=False),
    sa.Column('sign_base64', sa.Text(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('salary', sa.String(), nullable=False),
    sa.Column('default_wage', sa.Integer(), nullable=False),
    sa.Column('start_period', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_period', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_id'), 'contract', ['id'], unique=False)
    op.create_table('worklog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('wage', sa.Integer(), nullable=False),
    sa.Column('working_date_str', sa.String(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worklog_id'), 'worklog', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worklog_id'), table_name='worklog')
    op.drop_table('worklog')
    op.drop_index(op.f('ix_contract_id'), table_name='contract')
    op.drop_table('contract')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_employee_id'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_draft_id'), table_name='draft')
    op.drop_table('draft')
    # ### end Alembic commands ###
