"""delete is_admin

Revision ID: 88e31d4f3d01
Revises: 9b39f69cb21b
Create Date: 2024-01-16 18:36:30.419438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88e31d4f3d01'
down_revision: Union[str, None] = '9b39f69cb21b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
