"""delete has_team column

Revision ID: 8a98b9efd978
Revises: 88e31d4f3d01
Create Date: 2024-01-16 19:27:09.151996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a98b9efd978'
down_revision: Union[str, None] = '88e31d4f3d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_team')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_team', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
