"""Update explanation from group

Revision ID: 9e5514f81fae
Revises: e54221dc5c0e
Create Date: 2023-08-14 22:02:02.139511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5514f81fae'
down_revision: Union[str, None] = 'e54221dc5c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'explanation',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'explanation',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
